# Generated by Django 3.2.3 on 2021-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(verbose_name='deposit date time'),
        ),
    ]
