# Generated by Django 3.2.5 on 2021-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_deposit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='cost',
            new_name='amount',
        ),
    ]
