# Generated by Django 3.2.5 on 2021-07-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchasetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchases.purchasetype'),
        ),
    ]
